apiVersion: v1
kind: Service
metadata:
  name: patient-timeline-api-service
  namespace: doolittle-health
  labels:
    app: patient-timeline-api
spec:
  selector:
    app: patient-timeline-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
