apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patient-timeline-data-pvc
  namespace: doolittle-health
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
